// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingDeploy = `-- name: GetPendingDeploy :one
SELECT id, service_id, slot, status, commit_sha, commit_message, pushed_at,
       started_at, finished_at, created_at
FROM deploys
WHERE service_id = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingDeploy(ctx context.Context, serviceID string) (Deploy, error) {
	row := q.db.QueryRow(ctx, getPendingDeploy, serviceID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeploy = `-- name: InsertDeploy :one
INSERT INTO deploys (id, service_id, commit_sha, commit_message, pushed_at, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, service_id, slot, status, commit_sha, commit_message, pushed_at,
          started_at, finished_at, created_at
`

type InsertDeployParams struct {
	ID            string
	ServiceID     string
	CommitSha     string
	CommitMessage string
	PushedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDeploy(ctx context.Context, arg InsertDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, insertDeploy,
		arg.ID,
		arg.ServiceID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.PushedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingDeploys = `-- name: ListPendingDeploys :many
SELECT id, service_id, slot, status, commit_sha, commit_message, pushed_at,
       started_at, finished_at, created_at
FROM deploys
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingDeploys(ctx context.Context) ([]Deploy, error) {
	rows, err := q.db.Query(ctx, listPendingDeploys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slot,
			&i.Status,
			&i.CommitSha,
			&i.CommitMessage,
			&i.PushedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceRow = `-- name: LockServiceRow :one
SELECT id FROM services WHERE id = $1 FOR UPDATE
`

// Acquires a row-level lock on the service to serialise concurrent deploy enqueues.
func (q *Queries) LockServiceRow(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockServiceRow, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const upgradePendingDeploy = `-- name: UpgradePendingDeploy :one
UPDATE deploys
SET commit_sha = $2, commit_message = $3, pushed_at = $4
WHERE id = $1
RETURNING id, service_id, slot, status, commit_sha, commit_message, pushed_at,
          started_at, finished_at, created_at
`

type UpgradePendingDeployParams struct {
	ID            string
	CommitSha     string
	CommitMessage string
	PushedAt      pgtype.Timestamptz
}

func (q *Queries) UpgradePendingDeploy(ctx context.Context, arg UpgradePendingDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, upgradePendingDeploy,
		arg.ID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.PushedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
