// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployLock = `-- name: CreateDeployLock :exec
INSERT INTO deploy_locks (deploy_id, expires_at) VALUES ($1, $2)
`

type CreateDeployLockParams struct {
	DeployID  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateDeployLock(ctx context.Context, arg CreateDeployLockParams) error {
	_, err := q.db.Exec(ctx, createDeployLock, arg.DeployID, arg.ExpiresAt)
	return err
}

const getDeployByID = `-- name: GetDeployByID :one
SELECT id, service_id, slot, status, commit_sha, commit_message, pushed_at,
       started_at, finished_at, created_at
FROM deploys WHERE id = $1
`

func (q *Queries) GetDeployByID(ctx context.Context, id string) (Deploy, error) {
	row := q.db.QueryRow(ctx, getDeployByID, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeploy = `-- name: GetPendingDeploy :one
SELECT id, service_id, slot, status, commit_sha, commit_message, pushed_at,
       started_at, finished_at, created_at
FROM deploys
WHERE service_id = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingDeploy(ctx context.Context, serviceID string) (Deploy, error) {
	row := q.db.QueryRow(ctx, getPendingDeploy, serviceID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeploy = `-- name: InsertDeploy :one
INSERT INTO deploys (id, service_id, commit_sha, commit_message, pushed_at, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, service_id, slot, status, commit_sha, commit_message, pushed_at,
          started_at, finished_at, created_at
`

type InsertDeployParams struct {
	ID            string
	ServiceID     string
	CommitSha     string
	CommitMessage string
	PushedAt      pgtype.Timestamptz
}

func (q *Queries) InsertDeploy(ctx context.Context, arg InsertDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, insertDeploy,
		arg.ID,
		arg.ServiceID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.PushedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingDeploys = `-- name: ListPendingDeploys :many
SELECT id, service_id, slot, status, commit_sha, commit_message, pushed_at,
       started_at, finished_at, created_at
FROM deploys
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingDeploys(ctx context.Context) ([]Deploy, error) {
	rows, err := q.db.Query(ctx, listPendingDeploys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Slot,
			&i.Status,
			&i.CommitSha,
			&i.CommitMessage,
			&i.PushedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockServiceRow = `-- name: LockServiceRow :one
SELECT id FROM services WHERE id = $1 FOR UPDATE
`

// Acquires a row-level lock on the service to serialise concurrent deploy enqueues.
func (q *Queries) LockServiceRow(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockServiceRow, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const releaseDeployLock = `-- name: ReleaseDeployLock :exec
UPDATE deploy_locks SET released_at = NOW() WHERE deploy_id = $1 AND released_at IS NULL
`

func (q *Queries) ReleaseDeployLock(ctx context.Context, deployID string) error {
	_, err := q.db.Exec(ctx, releaseDeployLock, deployID)
	return err
}

const setDeployBuilding = `-- name: SetDeployBuilding :exec
UPDATE deploys SET status = 'building', slot = $2, started_at = NOW() WHERE id = $1
`

type SetDeployBuildingParams struct {
	ID   string
	Slot pgtype.Text
}

func (q *Queries) SetDeployBuilding(ctx context.Context, arg SetDeployBuildingParams) error {
	_, err := q.db.Exec(ctx, setDeployBuilding, arg.ID, arg.Slot)
	return err
}

const setDeployTerminal = `-- name: SetDeployTerminal :exec
UPDATE deploys SET status = $2, finished_at = NOW() WHERE id = $1
`

type SetDeployTerminalParams struct {
	ID     string
	Status string
}

func (q *Queries) SetDeployTerminal(ctx context.Context, arg SetDeployTerminalParams) error {
	_, err := q.db.Exec(ctx, setDeployTerminal, arg.ID, arg.Status)
	return err
}

const upgradePendingDeploy = `-- name: UpgradePendingDeploy :one
UPDATE deploys
SET commit_sha = $2, commit_message = $3, pushed_at = $4
WHERE id = $1
RETURNING id, service_id, slot, status, commit_sha, commit_message, pushed_at,
          started_at, finished_at, created_at
`

type UpgradePendingDeployParams struct {
	ID            string
	CommitSha     string
	CommitMessage string
	PushedAt      pgtype.Timestamptz
}

func (q *Queries) UpgradePendingDeploy(ctx context.Context, arg UpgradePendingDeployParams) (Deploy, error) {
	row := q.db.QueryRow(ctx, upgradePendingDeploy,
		arg.ID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.PushedAt,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Slot,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.PushedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
