// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package infra

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Service struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshKeyPath     string
	CreatedAt      pgtype.Timestamptz
}
