// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package infra

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deploy struct {
	ID            string
	ServiceID     string
	Slot          pgtype.Text
	Status        string
	CommitSha     string
	CommitMessage string
	PushedAt      pgtype.Timestamptz
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type DeployLock struct {
	DeployID   string
	LockedAt   pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
}

type Service struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshKeyPath     string
	CreatedAt      pgtype.Timestamptz
	BluePort       int32
	GreenPort      int32
	ContainerPort  int32
	ActiveSlot     pgtype.Text
}
