// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const existsByDomain = `-- name: ExistsByDomain :one
SELECT EXISTS (
    SELECT 1 FROM services WHERE domain = $1
) AS exists
`

func (q *Queries) ExistsByDomain(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByDomain, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getService = `-- name: GetService :one
SELECT id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_key_path, created_at
FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.WebhookSecret,
		&i.Host,
		&i.SshUser,
		&i.SshKeyPath,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_key_path, created_at
FROM services
ORDER BY created_at DESC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.Domain,
			&i.HealthCheckUrl,
			&i.WebhookSecret,
			&i.Host,
			&i.SshUser,
			&i.SshKeyPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveService = `-- name: SaveService :exec
INSERT INTO services (id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_key_path, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type SaveServiceParams struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshKeyPath     string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) SaveService(ctx context.Context, arg SaveServiceParams) error {
	_, err := q.db.Exec(ctx, saveService,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Domain,
		arg.HealthCheckUrl,
		arg.WebhookSecret,
		arg.Host,
		arg.SshUser,
		arg.SshKeyPath,
		arg.CreatedAt,
	)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET name = $2, health_check_url = $3
WHERE id = $1
`

type UpdateServiceParams struct {
	ID             string
	Name           string
	HealthCheckUrl string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.Exec(ctx, updateService, arg.ID, arg.Name, arg.HealthCheckUrl)
	return err
}
