// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const existsByDomain = `-- name: ExistsByDomain :one
SELECT EXISTS (
    SELECT 1 FROM services WHERE domain = $1
) AS exists
`

func (q *Queries) ExistsByDomain(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByDomain, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getService = `-- name: GetService :one
SELECT id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_private_key, blue_port, green_port, container_port, compose_service, active_slot, created_at
FROM services
WHERE id = $1
`

type GetServiceRow struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshPrivateKey  string
	BluePort       int32
	GreenPort      int32
	ContainerPort  int32
	ComposeService string
	ActiveSlot     pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetService(ctx context.Context, id string) (GetServiceRow, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i GetServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoUrl,
		&i.Domain,
		&i.HealthCheckUrl,
		&i.WebhookSecret,
		&i.Host,
		&i.SshUser,
		&i.SshPrivateKey,
		&i.BluePort,
		&i.GreenPort,
		&i.ContainerPort,
		&i.ComposeService,
		&i.ActiveSlot,
		&i.CreatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_private_key, blue_port, green_port, container_port, compose_service, active_slot, created_at
FROM services
ORDER BY created_at DESC
`

type ListServicesRow struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshPrivateKey  string
	BluePort       int32
	GreenPort      int32
	ContainerPort  int32
	ComposeService string
	ActiveSlot     pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoUrl,
			&i.Domain,
			&i.HealthCheckUrl,
			&i.WebhookSecret,
			&i.Host,
			&i.SshUser,
			&i.SshPrivateKey,
			&i.BluePort,
			&i.GreenPort,
			&i.ContainerPort,
			&i.ComposeService,
			&i.ActiveSlot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveService = `-- name: SaveService :exec
INSERT INTO services (id, name, repo_url, domain, health_check_url, webhook_secret, host, ssh_user, ssh_private_key, blue_port, green_port, container_port, compose_service, active_slot, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
`

type SaveServiceParams struct {
	ID             string
	Name           string
	RepoUrl        string
	Domain         string
	HealthCheckUrl string
	WebhookSecret  string
	Host           string
	SshUser        string
	SshPrivateKey  string
	BluePort       int32
	GreenPort      int32
	ContainerPort  int32
	ComposeService string
	ActiveSlot     pgtype.Text
}

func (q *Queries) SaveService(ctx context.Context, arg SaveServiceParams) error {
	_, err := q.db.Exec(ctx, saveService,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Domain,
		arg.HealthCheckUrl,
		arg.WebhookSecret,
		arg.Host,
		arg.SshUser,
		arg.SshPrivateKey,
		arg.BluePort,
		arg.GreenPort,
		arg.ContainerPort,
		arg.ComposeService,
		arg.ActiveSlot,
	)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET name = $2, health_check_url = $3
WHERE id = $1
`

type UpdateServiceParams struct {
	ID             string
	Name           string
	HealthCheckUrl string
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.Exec(ctx, updateService, arg.ID, arg.Name, arg.HealthCheckUrl)
	return err
}

const updateServiceActiveSlot = `-- name: UpdateServiceActiveSlot :exec
UPDATE services SET active_slot = $2 WHERE id = $1
`

type UpdateServiceActiveSlotParams struct {
	ID         string
	ActiveSlot pgtype.Text
}

func (q *Queries) UpdateServiceActiveSlot(ctx context.Context, arg UpdateServiceActiveSlotParams) error {
	_, err := q.db.Exec(ctx, updateServiceActiveSlot, arg.ID, arg.ActiveSlot)
	return err
}
